notifications:
  email:
    on_success: never
language: cpp
sudo: false
python:
  - "3.6"
os:
  - osx
env:
  global:
    - NINJA_STATUS="[%p %u/%t@%o %r]"
    - PROJECT_NAME=${PWD##*/}
  matrix:
    - BUILD_TYPE=Debug OPTIONAL=ON
    - BUILD_TYPE=Release OPTIONAL=ON
    - BUILD_TYPE=Debug OPTIONAL=OFF
    - BUILD_TYPE=Release OPTIONAL=OFF
matrix:
  fast_finish: true
before_install:
        #  - brew update
  - pyenv install 3.6.6
  - pyenv global 3.6.6
  - python3 -c "import sys; print(sys.version)"
  - python -c "import sys; print(sys.version)"
  - brew outdated cmake || brew upgrade cmake
  # We need to install gcc before hdf5 because otherwise hdf5 will fail.
  # The or statement is a hack to ensure we override the existing gcc without
  # having an error
  - brew install gcc || brew link --overwrite gcc
  #- brew install numpy@1.16 && brew link --overwrite numpy@1.16
  #- brew list --versions numpy
  #- find /usr/local/lib |grep numpy
  - brew install cppcheck doxygen ninja
  - brew list hdf5@1.10 || brew install hdf5@1.10
    #- brew switch hdf5 1.10.6_1
  - brew install boost-python
  - brew install lcov
  - ls -la  /usr/local/Cellar/hdf5@1.10/1.10.6_1
  - brew unlink numpy@1.19
  - pip3 install numpy==1.17.3
script:
  - pip install gcovr
  - mkdir $BUILD_TYPE
  - cd $BUILD_TYPE
  - HDF5_ROOT=/usr/local/Cellar/hdf5@1.10/1.10.6_1 cmake -GNinja -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DEXTLIB_FROM_SUBMODULES=ON ..
  - ninja all && ninja $PROJECT_NAME-tests && ninja smoketests
